### ISSUE TITLE
Missing TrainingIteratorRandom in utils.py

### ISSUE THREAD

**Issue by luffycodes** [FrancisGregoire/parSentExtract#3]
Traceback (most recent call last):
  File "train.py", line 268, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 196, in main
    train_iterator = utils.TrainingIteratorRandom(parallel_data, FLAGS.num_negative)

**Comment by FrancisGregoire** [comment]
Done. Just had to update utils.TraininingIteratorRandom to utils.TrainingIterator.

**Comment by luffycodes** [comment]
Thanks !
